.import __JSRTBL__

_print = __JSRTBL__+0
_input = __JSRTBL__+3
_cmpstr = __JSRTBL__+6
_memclr = __JSRTBL__+9
_memcpy = __JSRTBL__+12
_fload = __JSRTBL__+15
_fsave = __JSRTBL__+18
_load_config = __JSRTBL__+21
_save_config = __JSRTBL__+24
_printip = __JSRTBL__+27
_listen = __JSRTBL__+30
_stopserver = __JSRTBL__+33
_connect = __JSRTBL__+36

ARGS = $e0

PARAM1 = $fa
PARAM2 = $fc
RESULT = $ff

netdrv_flag = $f306
